name: Choose your adventure

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - name: Git checkout
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Deps
      run: |
        cd ./api && npm install && cd ..
        cd ./frontend && npm install
    
    - name: Test API
      run: cd api && npm test
        
    - name: Test Frontend Unit
      env:
        CI: false
      run: |
        cd frontend && npm run build
        && npm run test
